import java.time.Duration;

public class Ride {

    private String id; // key for equality and hashing
    private String name;
    private RideType rideType;
    private long dispatchTime;
    private long ridersPerDispatch;

    public Ride() {
    }
    
    public Ride(String id, String name) {
    	this.id  = id;
    	this.name  = name;
    }

    public Ride(String id, String name, RideType rideType, long dispatchTime, long ridersPerDispatch) {
        super();
        this.id = id;
        this.name = name;
        this.rideType = rideType;
        this.dispatchTime = dispatchTime;
        this.ridersPerDispatch = ridersPerDispatch;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public RideType getRideType() {
        return rideType;
    }

    public void setRideType(RideType rideType) {
        this.rideType = rideType;
    }

    public long getDispatchTime() {
        return dispatchTime;
    }

    public void setDispatchTime(long dispatchTime) {
        this.dispatchTime = dispatchTime;
    }

    public long getRidersPerDispatch() {
        return ridersPerDispatch;
    }

    public void setRidersPerDispatch(long ridersPerDispatch) {
        this.ridersPerDispatch = ridersPerDispatch;
    }

    // hashCode() and equals() generated by Eclipse
    // still should following our standards and style!

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Ride other = (Ride) obj;
        if (id == null) {
            if (other.id != null) {
                return false;
            }
        }
        else if (!id.equals(other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Ride [id=" + id + ", name=" + name + ", rideType=" + rideType + ", dispatchTime=" + dispatchTime
                + ", ridersPerDispatch=" + ridersPerDispatch + "]";
    }

}
